import Head from 'next/head'
import {useEffect} from "react"
import useSession from "../hooks/auth/useSession"
import { useSelector, useDispatch } from 'react-redux'
import serverProps from "../utils/serverProps";
import {selectAuthToken,selectAuthStatus} from '../features/auth/authSlice'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

import { useTranslation, Trans } from 'next-i18next'
import { getTranslations } from '../utils/getTranslations';
import HomeSlider from '../features/home/HomeSlider';
export default function Home(props) {
  let authToken = useSelector(selectAuthToken)
  const { t } = useTranslation('')
  const authStatus = useSelector(selectAuthStatus);
  useSession(props.sessionRefresh)

  // const token = useSelector(selectCurrentToken)
  useEffect(() => {
    // Perform localStorage action
    // alert("masuk")


  }, [])
  return (
    <>
      <Head>
        <title>Bagus loh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <HomeSlider></HomeSlider>
      </div>
      <div className="hero min-h-screen bg-base-200">
        <div className="hero-content text-center">
          <div className="max-w-md">
            <h1 className="text-5xl font-bold"> {t('common:h1')}</h1>
            <p className="py-6">
              Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda
              excepturi exercitationem quasi. In deleniti eaque aut repudiandae et a
              id nisi.
            </p>

            <div className="skeleton rounded bg-skeleton p-4">
              <div className="w-1/2 h-4 my-1"></div>
              <div className="w-full h-4 my-1"></div>
              <div className="w-3/4 h-4 my-1"></div>
            </div>
        
        
            <button className="btn btn-primary">Get Started</button>
          
          </div>
        </div>
      </div>

    </>
  )
}
export async function getServerSideProps(context) {
  // do custom page stuff...

    const locale = context.locale; 
    let propGlobal =  await serverProps(context,false)


    let propPlus = {  }
    
    
    let props = {...propGlobal.props ,...propPlus};


    return {props};
}
